[build]
  command = "npm run build"
  publish = "out"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"
  NETLIFY_USE_YARN = "false"
  NEXT_PUBLIC_API_URL = "/.netlify/functions/api"
  NETLIFY_SKIP_NEXT_PLUGIN = "true"

# Handle API requests
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# Handle client-side routing - must be last
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# JavaScript MIME types
[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/_next/static/*.js"
  [headers.values]
    Content-Type = "application/javascript"
    Cache-Control = "public, max-age=31536000, immutable"
